name: 'Docs Builds'
description: 'Builds docs and pushes them to a separate branch'
author: 'Spectacles'
inputs:
  docsOutput:
    description: Location of the generated docs files.
    default: docs
  branch:
    description: Target branch to push docs to.
    default: gh-pages
  targetDirectory:
    description: Directory in which to place docs files.
    default: echo ${{ github.ref }} | cut -d / -f 3-
  docsCommand:
    description: Command that generates the docs files.
    default: npm run docs
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docsOutput }}
    - ${{ inputs.branch }}
    - ${{ inputs.targetDirectory }}
    - ${{ inputs.docsCommand }}
