name: 'Docs Builds'
description: 'Builds docs and pushes them to a separate branch'
author: 'Spectacles'
inputs:
  docs-output:
    description: Location of the generated docs files.
    default: docs
  branch:
    description: Target branch to push docs to.
    default: gh-pages
  target-directory:
    description: Directory in which to place docs files.
    default: echo ${{ github.ref }} | cut -d / -f 3-
  docs-command:
    description: Command that generates the docs files.
    default: npm run docs
  github-token:
    description: Your GitHub token to deploy docs with.
    required: true
runs:
  using: node12
  main: dist/index.js
